make update-me aware of git worktrees

diff --git a/update-me b/update-me
--- a/update-me
+++ b/update-me
@@ -1,6 +1,7 @@
 #!/bin/bash
 ###################################################################
 # Canonical source: https://github.com/utoddl/update-ansible-git/ #
+# File: ./update-me                                               #
 ###################################################################
 
 # Bring local branches up-to-date with their corresponding remotes.
@@ -102,6 +103,7 @@ function vrun() {
   ) 3>&1
 }
 
+# vrunz() is like vrun but with timeout constraints.
 function vrunz() {
   echo "${boldon}[${pwdbase}]\$" "${@}" "${boldoff}"
   ( set -o pipefail
@@ -109,6 +111,7 @@ function vrunz() {
   ) 3>&1
 }
 
+# vruns() calls vrunz() with back-off retries in case of command timeouts.
 function vruns() {
   local tries=0
   local rc=0
@@ -176,7 +179,13 @@ for remote in $(git remote) ; do
   }
 done
 
-for branch in $(git for-each-ref '--format=%(refname:short)' refs/heads) ; do
+for branch_wtp in $(git for-each-ref '--format=%(refname:short):%(worktreepath)' refs/heads) ; do
+  branch="${branch_wtp%:*}"   # the branch name is left of the colon; the worktreepath is to the right.
+  wtp="$(realpath -q --canonicalize-missing "${branch_wtp#*:}" )"
+  if [ -n "$wtp" ] && [ "${PWD}" != "$wtp" ] ; then
+    echo -e "${brownon}Skipping branch '$branch'; worktree checked out elsewhere ${coloroff}" >&2
+    continue
+  fi
   if ( [[ "$branch_current" = "$branch" ]] && \
       echo -e "${brownon}On branch '$branch'${coloroff}") || vruns git checkout "$branch" ; then
     branch_current="$branch"
@@ -187,7 +196,7 @@ for branch in $(git for-each-ref '--format=%(refname:short)' refs/heads) ; do
         # Pull in the roles and collections requirements.yml bit
         # only on a branch that is the default for a remote.
         # There's normally only one of these.
-                                        # shellcheck disable=SC2046  # Left unquoted to enable word splitting
+        # shellcheck disable=SC2046  # Left unquoted to enable word splitting
         # shellcheck disable=SC2034  # Unused variables left for readability
         branch_remote_default=$( set -- $(git ls-remote --symref "${branch_remote%/*}" HEAD); test "$1" = "ref:"  && echo "$2" )
       fi
@@ -207,12 +216,14 @@ branch_final=$(git rev-parse --abbrev-ref HEAD)
 if [ -z "$quick" ] ; then
   if [ -f roles/requirements.yml ] ; then
     force=$fflag  # '--force'
+    # shellcheck disable=SC2086
     vruns ansible-galaxy install -r roles/requirements.yml $rolespath $force
   fi
 
   if [ -f collections/requirements.yml ] ; then
     force="$fflag"  # '--force' maybe '--force-with-deps' someday.
     # export ANSIBLE_COLLECTIONS_PATH=./collections
+    # shellcheck disable=SC2086
     vruns ansible-galaxy collection install -r collections/requirements.yml $collectionspath $force
   fi
 fi
